import { useMemo, useState } from "react";
import { ArrowLeft, ArrowUpLeft, Bell, BookOpen, Check, ChevronDown, Clock3, GraduationCap, LayoutDashboard, LockKeyhole, Menu, Play, Sparkles, Star, Target, Trophy, Users, X } from "lucide-react";

type Track = { title: string; subtitle: string; tone: string };
type Course = { title: string; subject: string; grade: string; teacher: string; lessons: number; level: string; tone: string };

const tracks: Track[] = [
  { title: "الثانوية العامة", subtitle: "أولى · تانية · تالتة", tone: "violet" },
  { title: "البكالوريا", subtitle: "طب · هندسة · أعمال · فنون", tone: "mint" },
  { title: "الإعدادية", subtitle: "ابني الأساس الصح", tone: "orange" },
];
const teachers = [
  { name: "أحمد سامي", subject: "رياضيات", meta: "شرح بسيط · 12 كورس", mark: "AS", tone: "violet" },
  { name: "مريم خالد", subject: "لغة عربية", meta: "نحو وبلاغة · 8 كورسات", mark: "MK", tone: "orange" },
  { name: "عمر فوزي", subject: "فيزياء", meta: "فهم قبل الحفظ · 10 كورسات", mark: "OF", tone: "blue" },
  { name: "سلمى عادل", subject: "Python & JS", meta: "برمجة للمستقبل · 6 كورسات", mark: "SA", tone: "mint" },
];
const courses: Course[] = [
  { title: "أساسيات التفاضل والتكامل", subject: "رياضيات", grade: "تالتة ثانوي", teacher: "أحمد سامي", lessons: 24, level: "متقدم", tone: "violet" },
  { title: "القراءة والنصوص", subject: "لغة عربية", grade: "تانية ثانوي", teacher: "مريم خالد", lessons: 18, level: "متوسط", tone: "orange" },
  { title: "الميكانيكا من الصفر", subject: "فيزياء", grade: "تالتة ثانوي", teacher: "عمر فوزي", lessons: 21, level: "متقدم", tone: "blue" },
  { title: "Python للمبتدئين", subject: "برمجة", grade: "بكالوريا", teacher: "سلمى عادل", lessons: 16, level: "مبتدئ", tone: "mint" },
];

export default function Mirqah() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [authOpen, setAuthOpen] = useState<"login" | "signup" | null>(null);
  const [track, setTrack] = useState("الكل");
  const [courseFilter, setCourseFilter] = useState("الكل");
  const [joined, setJoined] = useState(false);
  const visibleCourses = useMemo(() => courseFilter === "الكل" ? courses : courses.filter(course => course.subject === courseFilter), [courseFilter]);
  return <div className="mirqah-app" dir="rtl">
    <header className="mirqah-header"><a className="mirqah-logo" href="#mirqah-top"><span><GraduationCap size={20} /></span><strong>مِرقاة</strong><small>LEARN WITH PURPOSE</small></a><nav className={menuOpen ? "mirqah-nav open" : "mirqah-nav"}><a href="#paths" onClick={() => setMenuOpen(false)}>المسارات</a><a href="#courses" onClick={() => setMenuOpen(false)}>الكورسات</a><a href="#teachers" onClick={() => setMenuOpen(false)}>المدرسين</a><a href="#progress" onClick={() => setMenuOpen(false)}>تقدمك</a><button className="mirqah-nav-login" onClick={() => setAuthOpen("login")}>سجل دخول</button><button className="mirqah-nav-cta" onClick={() => setAuthOpen("signup")}>ابدأ مجانًا <ArrowLeft size={15} /></button></nav><button className="mirqah-menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="القائمة">{menuOpen ? <X /> : <Menu />}</button></header>
    <main id="mirqah-top">
      <section className="mirqah-hero"><div className="mirqah-hero-copy"><span className="mirqah-label"><i /> THE SMART WAY TO LEARN</span><h1>مش تحفظ.<br /><em>افهم واطلع.</em></h1><p>مِرقاة منصة تعليمية بتخلي المذاكرة أوضح، أهدى، وأقرب للنتيجة. مدرسين فاهمين، كورسات مرتبة، وتقدم تقدر تشوفه.</p><div className="mirqah-hero-actions"><button className="mirqah-primary" onClick={() => setAuthOpen("signup")}>ابدأ رحلتك <ArrowLeft size={17} /></button><a className="mirqah-text-link" href="#courses">استكشف الكورسات <ArrowUpLeft size={16} /></a></div><div className="mirqah-proof"><span><strong>4.9</strong><small><Star size={12} fill="currentColor" /> تقييم الطلاب</small></span><i /><span><strong>2.4k</strong><small>طالب بيتعلم معانا</small></span><i /><span><strong>96%</strong><small>نسبة إكمال</small></span></div></div><div className="mirqah-hero-visual"><div className="mirqah-orbit orbit-one" /><div className="mirqah-orbit orbit-two" /><div className="mirqah-orbit orbit-three" /><div className="mirqah-note note-one"><Target size={16} /><span>خطة واضحة<br /><b>لكل يوم</b></span></div><div className="mirqah-note note-two"><Trophy size={16} /><span>حقق هدفك<br /><b>خطوة بخطوة</b></span></div><div className="mirqah-board"><span>YOUR NEXT MOVE</span><strong>02</strong><em>حلّ · راجع · اتقدم</em><div><i /><i /><i /><i /></div></div><div className="mirqah-hero-badge"><Sparkles size={15} /> learning, redesigned</div></div></section>
      <section className="mirqah-marquee"><span>LEARN WITH PURPOSE</span><b>✳</b><span>MAKE PROGRESS VISIBLE</span><b>✳</b><span>LEARN WITH PURPOSE</span><b>✳</b><span>MAKE PROGRESS VISIBLE</span></section>
      <section className="mirqah-section mirqah-paths" id="paths"><div className="mirqah-section-head"><div><span className="mirqah-label"><i /> FIND YOUR PATH</span><h2>اختار طريقك.<br /><em>واحنا نرتب الباقي.</em></h2></div><p>مش كل طالب بيذاكر بنفس الطريقة. اختار مرحلتك وابدأ من مكانك.</p></div><div className="mirqah-track-tabs"><button className={track === "الكل" ? "active" : ""} onClick={() => setTrack("الكل")}>كل المسارات</button>{tracks.map(item => <button className={track === item.title ? "active" : ""} onClick={() => setTrack(item.title)} key={item.title}>{item.title}</button>)}</div><div className="mirqah-track-grid">{tracks.filter(item => track === "الكل" || item.title === track).map((item, index) => <button className={`mirqah-track-card ${item.tone}`} key={item.title} onClick={() => { setTrack(item.title); document.getElementById("courses")?.scrollIntoView({ behavior: "smooth" }); }}><span>0{index + 1}</span><div><small>{item.subtitle}</small><strong>{item.title}</strong><em>شوف المحتوى <ArrowLeft size={14} /></em></div><BookOpen size={28} /></button>)}</div></section>
      <section className="mirqah-section mirqah-courses" id="courses"><div className="mirqah-section-head"><div><span className="mirqah-label"><i /> CURATED FOR YOU</span><h2>كورسات<br /><em>توصلك.</em></h2></div><p>محتوى متقسم صح، عشان تعرف تبدأ منين وتوصل لفين.</p></div><div className="mirqah-filter-row">{["الكل", "رياضيات", "لغة عربية", "فيزياء", "برمجة"].map(item => <button className={courseFilter === item ? "active" : ""} onClick={() => setCourseFilter(item)} key={item}>{item}</button>)}</div><div className="mirqah-course-grid">{visibleCourses.map(course => <article className={`mirqah-course-card ${course.tone}`} key={course.title}><div className="mirqah-course-cover"><span>{course.subject}</span><strong>{course.tone === "mint" ? "{ }" : course.tone === "orange" ? "أ" : course.tone === "blue" ? "F" : "∫"}</strong><small>{course.level}</small></div><div className="mirqah-course-body"><div className="mirqah-course-meta"><span>{course.grade}</span><span><Clock3 size={12} /> {course.lessons} درس</span></div><h3>{course.title}</h3><p>شرح منظم، أمثلة محلولة، وتدريبات تساعدك تثبت الفكرة.</p><div className="mirqah-course-foot"><span>{course.teacher}</span><button onClick={() => setAuthOpen("signup")}>ادخل الكورس <ArrowLeft size={14} /></button></div></div></article>)}</div></section>
      <section className="mirqah-section mirqah-teachers" id="teachers"><div className="mirqah-section-head"><div><span className="mirqah-label"><i /> THE PEOPLE BEHIND THE LESSON</span><h2>مدرسين<br /><em>يفهموك.</em></h2></div><p>المدرس الصح مش بيقولك الإجابة بس، بيوصلك لطريقة التفكير.</p></div><div className="mirqah-teacher-grid">{teachers.map(teacher => <article className={`mirqah-teacher-card ${teacher.tone}`} key={teacher.name}><div className="mirqah-avatar">{teacher.mark}</div><small>{teacher.subject}</small><h3>{teacher.name}</h3><p>{teacher.meta}</p><button onClick={() => setAuthOpen("signup")}>عرض الكورسات <ArrowLeft size={14} /></button></article>)}</div></section>
      <section className="mirqah-progress-shell" id="progress"><div className="mirqah-progress-copy"><span className="mirqah-label"><i /> YOUR DASHBOARD</span><h2>خلي تقدمك<br /><em>قدام عينك.</em></h2><p>كل درس بتخلصه، كل اختبار بتحله، وكل خطوة بتقربك من هدفك — مِرقاة بيخليها واضحة.</p><button className="mirqah-primary" onClick={() => setAuthOpen("login")}>شوف تقدمك <LayoutDashboard size={16} /></button></div><div className="mirqah-dashboard"><div className="mirqah-dashboard-top"><span>مرحبًا يا بطل <Sparkles size={14} /></span><Bell size={16} /></div><div className="mirqah-progress-stat"><div><small>معدل الإنجاز</small><strong>68%</strong><span>أحسنت، كمل بنفس الإيقاع</span></div><div className="mirqah-progress-ring"><b>68</b><small>%</small></div></div><div className="mirqah-progress-bar"><i /></div><div className="mirqah-dashboard-list"><span><Check size={14} /> 12 درس مكتمل <b>هذا الأسبوع</b></span><span><Target size={14} /> هدف الأسبوع <b>4 / 6</b></span><span><Trophy size={14} /> سلسلة المذاكرة <b>7 أيام</b></span></div></div></section>
      <section className="mirqah-section mirqah-exams"><div className="mirqah-section-head"><div><span className="mirqah-label"><i /> TEST YOURSELF</span><h2>اختبر نفسك.<br /><em>اعرف مستواك.</em></h2></div><p>الاختبار مش نهاية الدرس، هو الطريقة اللي تعرف بيها إنك فهمت.</p></div><div className="mirqah-exam-grid"><article><span><Clock3 size={16} /> الخميس · 7:00 م</span><h3>اختبار التفاضل</h3><p>رياضيات · تالتة ثانوي</p><button onClick={() => setAuthOpen("login")}>سجل دخول للمشاركة <ArrowLeft size={14} /></button></article><article><span><Trophy size={16} /> أعلى نتيجة اليوم</span><h3>تحدي الفيزياء السريع</h3><p>15 سؤال · 12 دقيقة</p><button onClick={() => setAuthOpen("signup")}>ابدأ التدريب <Play size={14} /></button></article></div></section>
      <section className="mirqah-cta"><div><span className="mirqah-label"><i /> YOUR NEXT CHAPTER</span><h2>اللي جاي<br /><em>أحسن.</em></h2><p>اعمل حساب مجاني وابدأ أول خطوة في رحلتك.</p></div><button className="mirqah-primary" onClick={() => setAuthOpen("signup")}>اعمل حسابك مجانًا <ArrowLeft size={17} /></button></section>
    </main><footer className="mirqah-footer"><div><a className="mirqah-logo" href="#mirqah-top"><span><GraduationCap size={20} /></span><strong>مِرقاة</strong></a><p>منصة تعليمية بتخلي التقدم واضح.</p></div><div><small>EXPLORE</small><a href="#paths">المسارات</a><a href="#courses">الكورسات</a><a href="#teachers">المدرسين</a></div><div><small>ACCOUNT</small><button onClick={() => setAuthOpen("login")}>تسجيل الدخول</button><button onClick={() => setAuthOpen("signup")}>إنشاء حساب</button></div><span className="mirqah-footer-bottom">© 2026 MIRQAH · BUILT FOR BETTER DAYS</span></footer>
    {authOpen && <div className="mirqah-modal-backdrop" onClick={() => setAuthOpen(null)}><div className="mirqah-modal" onClick={event => event.stopPropagation()}><button className="mirqah-modal-close" onClick={() => setAuthOpen(null)}><X size={18} /></button><div className="mirqah-modal-icon"><LockKeyhole size={20} /></div><span className="mirqah-label"><i /> {authOpen === "login" ? "WELCOME BACK" : "START FRESH"}</span><h2>{authOpen === "login" ? "نورت مِرقاة." : "ابدأ من هنا."}</h2><p>{authOpen === "login" ? "سجل دخولك وكمل من حيث وقفت." : "حساب مجاني، ومحتوى يساعدك تتحرك."}</p><form onSubmit={event => { event.preventDefault(); setJoined(true); setAuthOpen(null); }}><label>{authOpen === "signup" ? "الاسم" : "البريد الإلكتروني"}<input required placeholder={authOpen === "signup" ? "اسمك بالكامل" : "you@email.com"} /></label>{authOpen === "signup" && <label>رقم الموبايل<input required placeholder="010 0000 0000" /></label>}<label>كلمة المرور<input required type="password" placeholder="••••••••" /></label><button className="mirqah-primary" type="submit">{authOpen === "login" ? "دخول المنصة" : "إنشاء حساب"}<ArrowLeft size={16} /></button></form><button className="mirqah-modal-switch" onClick={() => setAuthOpen(authOpen === "login" ? "signup" : "login")}>{authOpen === "login" ? "مش عندك حساب؟ اعمل حساب" : "عندك حساب؟ سجل دخول"}</button>{joined && <span className="mirqah-modal-success"><Check size={14} /> تم بنجاح، نبدأ الرحلة!</span>}</div></div>}
  </div>;
}
