import { useState } from "react";
import { ArrowLeft, ArrowRight, Bell, CalendarDays, Check, ChevronLeft, Clock3, LayoutDashboard, MessageCircle, MoreHorizontal, Plus, Search, Settings2, Sparkles, Users, X } from "lucide-react";

const services = [
  { name: "قصّة شعر كلاسيك", duration: "45 دقيقة", price: "180 ج.م", color: "lime" },
  { name: "قصّة + ذقن", duration: "60 دقيقة", price: "260 ج.م", color: "violet" },
  { name: "جلسة عناية كاملة", duration: "90 دقيقة", price: "390 ج.م", color: "orange" },
];
const bookings = [
  { time: "10:30", name: "عمر أحمد", service: "قصّة + ذقن", status: "مؤكد", tone: "lime" },
  { time: "12:00", name: "مروان علي", service: "جلسة عناية كاملة", status: "في الانتظار", tone: "orange" },
  { time: "01:30", name: "ياسين سمير", service: "قصّة شعر كلاسيك", status: "مؤكد", tone: "lime" },
  { time: "03:00", name: "كريم حسن", service: "قصّة + ذقن", status: "جديد", tone: "violet" },
];

function NabdaLogo() { return <a className="nabda-logo" href="/"><span className="nabda-mark"><Sparkles size={16} /></span><strong>نَبضة</strong><small>booking, made human.</small></a>; }

export default function Nabda() {
  const [view, setView] = useState<"dashboard" | "booking">("dashboard");
  const [booked, setBooked] = useState(false);
  const [selectedService, setSelectedService] = useState(services[1].name);
  const [selectedTime, setSelectedTime] = useState("12:00 م");
  return <div className="nabda-page">
    <header className="nabda-header"><NabdaLogo /><nav><button className={view === "dashboard" ? "active" : ""} onClick={() => setView("dashboard")}>لوحة التحكم</button><button className={view === "booking" ? "active" : ""} onClick={() => setView("booking")}>صفحة الحجز</button></nav><div className="nabda-header-actions"><span className="nabda-live"><i /> Demo preview</span><button className="nabda-icon"><Bell size={17} /></button><span className="nabda-avatar">HA</span></div></header>
    <main>
      {view === "dashboard" ? <section className="nabda-dashboard">
        <div className="nabda-welcome"><div><span className="nabda-eyebrow">MONDAY · 26 SEPTEMBER 2026</span><h1>صباح الخير يا حازم <span>✦</span></h1><p>عندك يوم مليان، بس كل حاجة تحت السيطرة.</p></div><button className="nabda-primary" onClick={() => setView("booking")}><Plus size={17} /> حجز جديد</button></div>
        <div className="nabda-stat-grid"><article><span className="nabda-stat-icon lime"><CalendarDays size={18} /></span><div><small>حجوزات اليوم</small><strong>24</strong><b>+18% <em>من الأسبوع اللي فات</em></b></div></article><article><span className="nabda-stat-icon violet"><Users size={18} /></span><div><small>عملاء جدد</small><strong>08</strong><b>+12% <em>من الأسبوع اللي فات</em></b></div></article><article><span className="nabda-stat-icon orange"><Clock3 size={18} /></span><div><small>ساعات محجوزة</small><strong>18.5</strong><b>92% <em>نسبة الإشغال</em></b></div></article><article><span className="nabda-stat-icon blue"><MessageCircle size={18} /></span><div><small>رسائل متابعة</small><strong>16</strong><b>جاهزة <em>للإرسال اليوم</em></b></div></article></div>
        <div className="nabda-main-grid"><section className="nabda-panel nabda-calendar-panel"><div className="nabda-panel-head"><div><span>AGENDA / TODAY</span><h2>مواعيد اليوم</h2></div><button><MoreHorizontal size={18} /></button></div><div className="nabda-date-strip"><button><ChevronLeft size={15} /></button>{["26", "27", "28", "29", "30"].map((day, i) => <div className={i === 0 ? "selected" : ""} key={day}><small>{["الإثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة"][i]}</small><strong>{day}</strong></div>)}<button><ChevronLeft size={15} /></button></div><div className="nabda-bookings">{bookings.map((booking) => <div className="nabda-booking" key={booking.time}><time>{booking.time}</time><span className={`nabda-booking-dot ${booking.tone}`} /><div><strong>{booking.name}</strong><small>{booking.service}</small></div><b className={booking.tone}>{booking.status}</b><button><MoreHorizontal size={16} /></button></div>)}</div><button className="nabda-link-button" onClick={() => setView("booking")}>عرض كل المواعيد <ArrowLeft size={15} /></button></section><section className="nabda-panel nabda-side-panel"><div className="nabda-panel-head"><div><span>QUICK VIEW</span><h2>خدماتك</h2></div><button><Plus size={17} /></button></div><div className="nabda-services">{services.map((service) => <div className="nabda-service" key={service.name}><span className={`nabda-service-icon ${service.color}`}><Sparkles size={15} /></span><div><strong>{service.name}</strong><small>{service.duration}</small></div><b>{service.price}</b></div>)}</div><div className="nabda-share"><div><strong>شارك رابط الحجز</strong><span>nabda.app/your-space</span></div><button onClick={() => setView("booking")}><ArrowLeft size={16} /></button></div></section></div>
        <section className="nabda-bottom-row"><div className="nabda-insight"><div className="nabda-insight-orb" /><span className="nabda-eyebrow">SMART INSIGHT</span><h2>الثلاثاء أكثر يوم<br /><em>بيتحجز عندك.</em></h2><p>جرّب تفتح مواعيد إضافية من 4 إلى 7 مساءً الأسبوع الجاي.</p><button onClick={() => setView("booking")}>شوف التفاصيل <ArrowLeft size={15} /></button></div><div className="nabda-activity"><div className="nabda-panel-head"><div><span>RECENT ACTIVITY</span><h2>آخر التحديثات</h2></div><Search size={17} /></div><div className="nabda-activity-list"><p><i className="lime" /><span><strong>سارة محمد</strong> أكدت حجزها الجديد<small>منذ 8 دقائق</small></span><Check size={15} /></p><p><i className="violet" /><span><strong>ياسين سمير</strong> انضم لعملائك<small>منذ 34 دقيقة</small></span><Users size={15} /></p><p><i className="orange" /><span><strong>رسالة تذكير</strong> جاهزة للإرسال<small>منذ ساعة</small></span><Bell size={15} /></p></div></div></section>
      </section> : <section className="nabda-booking-view"><div className="nabda-booking-brand"><NabdaLogo /><span>تجربة حجز بسيطة، من غير مكالمات.</span></div><div className="nabda-booking-layout"><div className="nabda-booking-copy"><span className="nabda-eyebrow">BOOK YOUR MOMENT</span><h1>وقتك<br /><em>مهم.</em></h1><p>اختار الخدمة والميعاد المناسب ليك، وإحنا نهتم بالباقي.</p><div className="nabda-trust"><span><Check size={14} /> تأكيد فوري</span><span><Check size={14} /> بدون انتظار</span></div></div><div className="nabda-form-card"><div className="nabda-form-top"><span>01 / 03</span><strong>احجز موعدك</strong></div>{booked ? <div className="nabda-success"><span><Check size={28} /></span><h2>تم الحجز بنجاح</h2><p>هنبعتلك تفاصيل الموعد على WhatsApp.</p><button className="nabda-primary" onClick={() => setBooked(false)}>حجز موعد آخر</button></div> : <><label>الاسم<input placeholder="اكتب اسمك" /></label><label>اختار الخدمة<select value={selectedService} onChange={(e) => setSelectedService(e.target.value)}>{services.map(service => <option key={service.name}>{service.name}</option>)}</select></label><label>اختار الميعاد<div className="nabda-times">{["10:30 ص", "12:00 م", "01:30 م", "03:00 م"].map(time => <button type="button" className={selectedTime === time ? "selected" : ""} onClick={() => setSelectedTime(time)} key={time}>{time}</button>)}</div></label><button className="nabda-primary nabda-submit" onClick={() => setBooked(true)}>تأكيد الحجز <ArrowLeft size={16} /></button></>}</div></div><button className="nabda-back-link" onClick={() => setView("dashboard")}><ArrowRight size={15} /> العودة للوحة التحكم</button></section>}
    </main>
    <footer className="nabda-footer"><NabdaLogo /><span>SCORPIUS PRODUCT DEMO · 2026</span><a href="/">صمّم منتجك مع SCORPIUS <ArrowLeft size={14} /></a></footer>
  </div>;
}
