import { useEffect, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, Bell, CalendarDays, Check, ChevronLeft, Clock3, LockKeyhole, MessageCircle, MoreHorizontal, Plus, Search, Sparkles, UserRound, Users, X } from "lucide-react";

const ADMIN_EMAIL = "yyh123456h@gmail.com";
const ADMIN_PASSWORD = "123456nabda";
const services = [
  { name: "قصّة شعر كلاسيك", duration: "45 دقيقة", price: "180 ج.م", color: "lime" },
  { name: "قصّة + ذقن", duration: "60 دقيقة", price: "260 ج.م", color: "violet" },
  { name: "جلسة عناية كاملة", duration: "90 دقيقة", price: "390 ج.م", color: "orange" },
];
const defaultBookings = [
  { time: "10:30", name: "عمر أحمد", service: "قصّة + ذقن", status: "مؤكد", tone: "lime" },
  { time: "12:00", name: "مروان علي", service: "جلسة عناية كاملة", status: "في الانتظار", tone: "orange" },
  { time: "01:30", name: "ياسين سمير", service: "قصّة شعر كلاسيك", status: "مؤكد", tone: "lime" },
  { time: "03:00", name: "كريم حسن", service: "قصّة + ذقن", status: "جديد", tone: "violet" },
];
type Booking = { time: string; name: string; service: string; status: string; tone: string };

function readBookings(): Booking[] { try { return JSON.parse(localStorage.getItem("nabda-bookings") || "null") || defaultBookings; } catch { return defaultBookings; } }
function NabdaLogo({ onMarkClick }: { onMarkClick?: () => void }) { return <a className="nabda-logo" href="/" onClick={event => { if (onMarkClick) { event.preventDefault(); onMarkClick(); } }}><span className="nabda-mark"><Sparkles size={16} /></span><strong>نَبضة</strong><small>booking, made human.</small></a>; }

export default function Nabda() {
  const [view, setView] = useState<"dashboard" | "booking">("dashboard");
  const [booked, setBooked] = useState(false);
  const [selectedService, setSelectedService] = useState(services[1].name);
  const [selectedTime, setSelectedTime] = useState("12:00 م");
  const [name, setName] = useState("");
  const [customer, setCustomer] = useState(() => localStorage.getItem("nabda-customer") || "");
  const [authOpen, setAuthOpen] = useState(false);
  const [adminOpen, setAdminOpen] = useState(false);
  const [adminUnlocked, setAdminUnlocked] = useState(false);
  const [authMode, setAuthMode] = useState<"login" | "register">("login");
  const [authError, setAuthError] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [phone, setPhone] = useState("");
  const [bookings, setBookings] = useState<Booking[]>(readBookings);
  const secretClicks = useRef(0);
  const secretTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => { if (customer) localStorage.setItem("nabda-customer", customer); }, [customer]);
  const secretClick = () => { secretClicks.current += 1; if (secretTimer.current) clearTimeout(secretTimer.current); secretTimer.current = setTimeout(() => { secretClicks.current = 0; }, 1300); if (secretClicks.current === 5) { secretClicks.current = 0; setAdminOpen(true); setAuthError(""); } };
  const submitAuth = (event: React.FormEvent) => { event.preventDefault(); setAuthError(""); if (adminOpen) { if (email.trim().toLowerCase() !== ADMIN_EMAIL || password !== ADMIN_PASSWORD) return setAuthError("الإيميل أو كلمة المرور غير صحيحة"); setAdminUnlocked(true); setAdminOpen(false); setView("dashboard"); return; } if (authMode === "register") { if (!name.trim() || phone.trim().length < 7) return setAuthError("اكتب الاسم ورقم موبايل صحيح"); setCustomer(name.trim()); setAuthOpen(false); } else { const saved = localStorage.getItem("nabda-customer-name") || name.trim(); if (!saved || password.length < 6) return setAuthError("اكتب الاسم وكلمة المرور للتجربة"); setCustomer(saved); setAuthOpen(false); } };
  const submitBooking = () => { if (!customer) return setAuthOpen(true); const next = { time: selectedTime, name: customer, service: selectedService, status: "جديد", tone: "violet" }; const updated = [next, ...bookings]; setBookings(updated); localStorage.setItem("nabda-bookings", JSON.stringify(updated)); setBooked(true); };
  const signOut = () => { setCustomer(""); localStorage.removeItem("nabda-customer"); setAdminUnlocked(false); };

  return <div className="nabda-page">
    <header className="nabda-header"><NabdaLogo onMarkClick={secretClick} /><nav><button className={view === "dashboard" ? "active" : ""} onClick={() => setView("dashboard")}>لوحة التحكم</button><button className={view === "booking" ? "active" : ""} onClick={() => setView("booking")}>صفحة الحجز</button></nav><div className="nabda-header-actions"><span className="nabda-live"><i /> {adminUnlocked ? "Admin mode" : "Live demo"}</span>{customer ? <button className="nabda-user-button" onClick={signOut}><UserRound size={15} /> {customer}</button> : <button className="nabda-user-button" onClick={() => setAuthOpen(true)}><UserRound size={15} /> دخول العميل</button>}<button className="nabda-icon"><Bell size={17} /></button><span className="nabda-avatar">HA</span></div></header>
    <main>
      {view === "dashboard" ? <section className="nabda-dashboard">
        <div className="nabda-welcome"><div><span className="nabda-eyebrow">MONDAY · 26 SEPTEMBER 2026</span><h1>{adminUnlocked ? "لوحة الأدمن تحت السيطرة" : "صباح الخير يا حازم"} <span>✦</span></h1><p>{adminUnlocked ? "تقدر تراجع العملاء والحجوزات المسجلة من نفس الجهاز." : "عندك يوم مليان، بس كل حاجة تحت السيطرة."}</p></div><button className="nabda-primary" onClick={() => setView("booking")}><Plus size={17} /> حجز جديد</button></div>
        <div className="nabda-stat-grid"><article><span className="nabda-stat-icon lime"><CalendarDays size={18} /></span><div><small>حجوزات اليوم</small><strong>{bookings.length}</strong><b>+18% <em>من الأسبوع اللي فات</em></b></div></article><article><span className="nabda-stat-icon violet"><Users size={18} /></span><div><small>عملاء مسجلين</small><strong>{new Set(bookings.map(item => item.name)).size}</strong><b>مباشر <em>من المتصفح</em></b></div></article><article><span className="nabda-stat-icon orange"><Clock3 size={18} /></span><div><small>ساعات محجوزة</small><strong>18.5</strong><b>92% <em>نسبة الإشغال</em></b></div></article><article><span className="nabda-stat-icon blue"><MessageCircle size={18} /></span><div><small>رسائل متابعة</small><strong>16</strong><b>جاهزة <em>للإرسال اليوم</em></b></div></article></div>
        <div className="nabda-main-grid"><section className="nabda-panel nabda-calendar-panel"><div className="nabda-panel-head"><div><span>AGENDA / TODAY</span><h2>{adminUnlocked ? "كل الحجوزات المسجلة" : "مواعيد اليوم"}</h2></div><button><MoreHorizontal size={18} /></button></div><div className="nabda-date-strip"><button><ChevronLeft size={15} /></button>{["26", "27", "28", "29", "30"].map((day, i) => <div className={i === 0 ? "selected" : ""} key={day}><small>{["الإثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة"][i]}</small><strong>{day}</strong></div>)}<button><ChevronLeft size={15} /></button></div><div className="nabda-bookings">{bookings.map((booking, index) => <div className="nabda-booking" key={`${booking.time}-${booking.name}-${index}`}><time>{booking.time}</time><span className={`nabda-booking-dot ${booking.tone}`} /><div><strong>{booking.name}</strong><small>{booking.service}</small></div><b className={booking.tone}>{booking.status}</b><button><MoreHorizontal size={16} /></button></div>)}</div><button className="nabda-link-button" onClick={() => setView("booking")}>عرض كل المواعيد <ArrowLeft size={15} /></button></section><section className="nabda-panel nabda-side-panel"><div className="nabda-panel-head"><div><span>QUICK VIEW</span><h2>خدماتك</h2></div><button><Plus size={17} /></button></div><div className="nabda-services">{services.map(service => <div className="nabda-service" key={service.name}><span className={`nabda-service-icon ${service.color}`}><Sparkles size={15} /></span><div><strong>{service.name}</strong><small>{service.duration}</small></div><b>{service.price}</b></div>)}</div><div className="nabda-share"><div><strong>شارك رابط الحجز</strong><span>/nabda</span></div><button onClick={() => setView("booking")}><ArrowLeft size={16} /></button></div></section></div>
        <section className="nabda-bottom-row"><div className="nabda-insight" onClick={secretClick}><div className="nabda-insight-orb" /><span className="nabda-eyebrow">SMART INSIGHT</span><h2>الثلاثاء أكثر يوم<br /><em>بيتحجز عندك.</em></h2><p>اضغط على هذه البطاقة 5 مرات بسرعة لفتح دخول الأدمن.</p><button onClick={() => setView("booking")}>شوف التفاصيل <ArrowLeft size={15} /></button></div><div className="nabda-activity"><div className="nabda-panel-head"><div><span>RECENT ACTIVITY</span><h2>آخر التحديثات</h2></div><Search size={17} /></div><div className="nabda-activity-list"><p><i className="lime" /><span><strong>{bookings[0]?.name || "عميل جديد"}</strong> أكد حجزه الجديد<small>منذ 8 دقائق</small></span><Check size={15} /></p><p><i className="violet" /><span><strong>عميل جديد</strong> انضم لعملائك<small>منذ 34 دقيقة</small></span><Users size={15} /></p><p><i className="orange" /><span><strong>رسالة تذكير</strong> جاهزة للإرسال<small>منذ ساعة</small></span><Bell size={15} /></p></div></div></section>
      </section> : <section className="nabda-booking-view"><div className="nabda-booking-brand"><NabdaLogo /><span>تجربة حجز بسيطة، من غير مكالمات.</span></div><div className="nabda-booking-layout"><div className="nabda-booking-copy"><span className="nabda-eyebrow">BOOK YOUR MOMENT</span><h1>وقتك<br /><em>مهم.</em></h1><p>اختار الخدمة والميعاد المناسب ليك، وإحنا نهتم بالباقي.</p><div className="nabda-trust"><span><Check size={14} /> تأكيد فوري</span><span><Check size={14} /> بدون انتظار</span></div></div><div className="nabda-form-card">{!customer ? <><div className="nabda-form-top"><span>LOGIN REQUIRED</span><strong>سجل دخولك للحجز</strong></div><div className="nabda-login-visual"><UserRound size={28} /><h2>خطوة واحدة وتكون جاهز</h2><p>سجّل حسابك علشان نحفظ بياناتك وحجوزاتك.</p><button className="nabda-primary" onClick={() => setAuthOpen(true)}>دخول العميل <ArrowLeft size={16} /></button></div></> : booked ? <div className="nabda-success"><span><Check size={28} /></span><h2>تم الحجز بنجاح</h2><p>الحجز محفوظ على هذا الجهاز باسم {customer}.</p><button className="nabda-primary" onClick={() => setBooked(false)}>حجز موعد آخر</button></div> : <><div className="nabda-form-top"><span>01 / 03</span><strong>احجز موعدك</strong></div><label>الاسم<input value={customer} readOnly /></label><label>اختار الخدمة<select value={selectedService} onChange={e => setSelectedService(e.target.value)}>{services.map(service => <option key={service.name}>{service.name}</option>)}</select></label><label>اختار الميعاد<div className="nabda-times">{["10:30 ص", "12:00 م", "01:30 م", "03:00 م"].map(time => <button type="button" className={selectedTime === time ? "selected" : ""} onClick={() => setSelectedTime(time)} key={time}>{time}</button>)}</div></label><button className="nabda-primary nabda-submit" onClick={submitBooking}>تأكيد الحجز <ArrowLeft size={16} /></button></>}</div></div><button className="nabda-back-link" onClick={() => setView("dashboard")}><ArrowRight size={15} /> العودة للوحة التحكم</button></section>}
    </main>
    <footer className="nabda-footer"><NabdaLogo onMarkClick={secretClick} /><span>SCORPIUS PRODUCT DEMO · 2026</span><a href="/">صمّم منتجك مع SCORPIUS <ArrowLeft size={14} /></a></footer>
    {((authOpen && !adminOpen) || adminOpen) && <div className="nabda-modal-backdrop" onClick={() => { setAuthOpen(false); setAdminOpen(false); }}><div className="nabda-modal" onClick={event => event.stopPropagation()}><button className="nabda-modal-close" onClick={() => { setAuthOpen(false); setAdminOpen(false); }}><X size={17} /></button><span className="nabda-modal-icon">{adminOpen ? <LockKeyhole size={20} /> : <UserRound size={20} />}</span><span className="nabda-eyebrow">{adminOpen ? "PRIVATE ADMIN ACCESS" : authMode === "register" ? "CREATE ACCOUNT" : "CUSTOMER LOGIN"}</span><h2>{adminOpen ? "دخول لوحة الأدمن" : authMode === "register" ? "اعمل حسابك" : "أهلًا بيك"}</h2><p>{adminOpen ? "الدخول السري لإدارة بيانات الحجز." : "بيانات بسيطة علشان نثبت حجزك ونحفظه."}</p><form onSubmit={submitAuth}>{!adminOpen && authMode === "register" && <label>الاسم<input value={name} onChange={event => { setName(event.target.value); localStorage.setItem("nabda-customer-name", event.target.value); }} required /></label>}{!adminOpen && authMode === "register" && <label>الموبايل<input value={phone} onChange={event => setPhone(event.target.value)} required /></label>}<label>الإيميل {adminOpen && <input type="email" value={email} onChange={event => setEmail(event.target.value)} required />}</label>{!adminOpen && <input className="nabda-hidden-field" value={email} onChange={event => setEmail(event.target.value)} />}<label>كلمة المرور<input type="password" value={password} onChange={event => setPassword(event.target.value)} minLength={6} required /></label>{authError && <strong className="nabda-auth-error">{authError}</strong>}<button className="nabda-primary nabda-submit">{adminOpen ? "دخول لوحة التحكم" : authMode === "register" ? "إنشاء الحساب" : "تسجيل الدخول"}<ArrowLeft size={16} /></button></form>{!adminOpen && <button className="nabda-auth-switch" onClick={() => { setAuthMode(authMode === "login" ? "register" : "login"); setAuthError(""); }}>{authMode === "login" ? "لسه جديد؟ اعمل حساب" : "عندي حساب بالفعل"}</button>}</div></div>}
  </div>;
}
