import { useEffect, useMemo, useState } from "react";
import { Activity, BarChart3, CalendarDays, CheckCircle2, Eye, FileText, FolderKanban, LogOut, MessageSquare, RefreshCw, ShieldCheck, Users, XCircle } from "lucide-react";
type Row = Record<string, any>; type Overview = { stats: { users: number; visits: number; reviews: number; pendingReviews: number; bookings: number; projects: number }; data: { users: Row[]; visits: Row[]; reviews: Row[]; bookings: Row[]; projects: Row[]; logs: Row[] } };
const empty: Overview = { stats: { users: 0, visits: 0, reviews: 0, pendingReviews: 0, bookings: 0, projects: 0 }, data: { users: [], visits: [], reviews: [], bookings: [], projects: [], logs: [] } };
const fmt = (v: unknown) => v ? new Date(String(v)).toLocaleString("ar-EG", { dateStyle: "medium", timeStyle: "short" }) : "—";
export default function ScorpiusAdmin() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [authenticated, setAuthenticated] = useState(false); const [overview, setOverview] = useState<Overview>(empty); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { setLoading(true); try { const r = await fetch("/api/admin-overview", { credentials: "include" }); if (r.status === 401) { setAuthenticated(false); return; } const body = await r.json(); if (!r.ok) throw new Error(body.error); setOverview(body); setAuthenticated(true); setError(""); } catch { setError("تعذر تحميل بيانات لوحة SCORPIUS الآن."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const login = async (e: React.FormEvent) => { e.preventDefault(); setLoading(true); setError(""); try { const r = await fetch("/api/admin-login", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); if (!r.ok) throw new Error(); await load(); } catch { setError("البريد أو كلمة المرور غير صحيحة."); setLoading(false); } };
  const logout = async () => { await fetch("/api/admin-logout", { method: "POST", credentials: "include" }); setAuthenticated(false); };
  const recent = useMemo(() => [...overview.data.visits].slice(0, 8), [overview.data.visits]);
  if (!authenticated) return <main className="sc-admin-login"><div className="sc-login-orbit" /><section><div className="sc-brand"><span>♏</span><strong>SCORPIUS</strong><small>PRIVATE CONTROL ROOM</small></div><p className="sc-kicker">SECURE ADMIN ACCESS</p><h1>كل ما يحدث<br /><em>تحت عينك.</em></h1><p className="sc-login-copy">لوحة واحدة لمتابعة الزوار، الآراء، الحجوزات، المشاريع، وسجل النشاط داخل SCORPIUS.</p><form onSubmit={login}><label>البريد الإلكتروني<input type="email" value={email} onChange={e => setEmail(e.target.value)} required placeholder="admin@scorpius.studio" /></label><label>كلمة المرور<input type="password" value={password} onChange={e => setPassword(e.target.value)} required /></label>{error && <div className="sc-error"><XCircle size={15} /> {error}</div>}<button className="sc-primary" disabled={loading}>{loading ? "جاري التحقق…" : "دخول لوحة الأدمن"}<ShieldCheck size={16} /></button></form><a href="/">العودة إلى الموقع</a></section></main>;
  const cards = [["الزوار", overview.stats.visits, Eye, "visits"], ["المستخدمون", overview.stats.users, Users, "users"], ["الآراء", overview.stats.reviews, MessageSquare, "reviews"], ["آراء تنتظر المراجعة", overview.stats.pendingReviews, FileText, "pending"], ["الحجوزات", overview.stats.bookings, CalendarDays, "bookings"], ["المشاريع", overview.stats.projects, FolderKanban, "projects"]] as const;
  return <main className="sc-admin-shell" dir="rtl"><aside><div className="sc-side-brand"><span>♏</span><strong>SCORPIUS</strong><small>ADMIN / CONTROL ROOM</small></div><p className="sc-side-label">المتابعة</p><nav><a className="active"><BarChart3 size={16} /> نظرة عامة</a><a href="#reviews"><MessageSquare size={16} /> آراء العملاء</a><a href="#bookings"><CalendarDays size={16} /> الحجوزات</a><a href="#activity"><Activity size={16} /> النشاط والزيارات</a></nav><button className="sc-logout" onClick={logout}><LogOut size={15} /> خروج آمن</button></aside><section className="sc-admin-main"><header><div><span className="sc-kicker">SCORPIUS / LIVE OVERVIEW</span><h1>صباح الخير، يا أدمن.</h1><p>كل أرقام ومحتوى الموقع في مكان واحد.</p></div><div className="sc-head-actions"><span><i /> اتصال آمن</span><button onClick={() => void load()}><RefreshCw size={15} /> تحديث</button></div></header><div className="sc-stat-grid">{cards.map(([label, value, Icon, key]) => <article key={key}><Icon size={18} /><small>{label}</small><strong>{value}</strong></article>)}</div><div className="sc-grid"><section className="sc-panel" id="activity"><div className="sc-panel-title"><div><span>TRAFFIC / RECENT</span><h2>آخر الزيارات</h2></div><Eye size={18} /></div><div className="sc-list">{recent.length ? recent.map(row => <div key={row.id}><span className="sc-avatar">↗</span><div><strong>{row.path}</strong><small>{fmt(row.created_at)}</small></div><b>زيارة</b></div>) : <em>لا توجد زيارات مسجلة بعد.</em>}</div></section><section className="sc-panel" id="reviews"><div className="sc-panel-title"><div><span>CLIENT VOICE</span><h2>آخر الآراء</h2></div><MessageSquare size={18} /></div><div className="sc-list">{overview.data.reviews.slice(0, 6).map(row => <div key={row.id}><span className="sc-avatar lime">★</span><div><strong>{row.name}</strong><small>{row.quote}</small></div><b className={row.status === "approved" ? "approved" : "pending"}>{row.status}</b></div>)}{!overview.data.reviews.length && <em>لا توجد آراء بعد.</em>}</div></section></div><section className="sc-panel sc-table-panel" id="bookings"><div className="sc-panel-title"><div><span>BOOKING PIPELINE</span><h2>آخر الحجوزات</h2></div><CalendarDays size={18} /></div><div className="sc-table-head"><span>العميل</span><span>الموعد</span><span>الحالة</span><span>تاريخ التسجيل</span></div>{overview.data.bookings.slice(0, 12).map(row => <div className="sc-table-row" key={row.id}><strong>{row.customer_name}<small>{row.customer_phone}</small></strong><span>{fmt(row.appointment_at)}</span><b>{row.status}</b><time>{fmt(row.created_at)}</time></div>)}{!overview.data.bookings.length && <em className="sc-empty">لا توجد حجوزات مسجلة.</em>}</section><footer><span>SCORPIUS ADMIN · DATA CONTROL</span><span>آخر تحديث: {new Date().toLocaleTimeString("ar-EG")}</span></footer></section></main>;
}
